---

# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :use_deep_dependencies: TRUE
  :build_root: build
  # :release_build: TRUE
  :test_file_prefix: Test

#:release_build:
#  :output: TempSensor.out
#  :use_assembly: FALSE

:environment: []

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :support:
    - test/support

:defines:
  :common: &common_defines
    - UNIT_TEST
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST
  :TestAdcHardwareSpecial:
    - *common_defines
    - TEST
    - DUMMY
  :use_test_definition: TRUE

# LIBRARIES
# These libraries are automatically injected into the build process. Those specified as
# common will be used in all types of builds. Otherwise, libraries can be injected in just
# tests or releases. These options are MERGED with the options in supplemental yaml files.
:libraries:
  :placement: :end
  :flag: "${1}"  # or "-L ${1}" for example
  :common: &common_libraries []
  :test:
    - *common_libraries
  :release:
    - *common_libraries

:cmock:
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

#:tools:
# Ceedling defaults to using gcc for compiling, linking, etc.
# As [:tools] is blank, gcc will be used (so long as it's in your system path)
# See documentation to configure a given toolchain for use

:tools_test_linker:
  :arguments:
    - -lm
:tools_gcov_linker:
  :arguments:
    - -lm
:gcov:
  :html_report_type: detailed
  #:merge_results: TRUE
  #:html_report: TRUE
  #:json_report: TRUE
  #:print_summary: TRUE
  #:text_report: TRUE
  # Specify the reports to generate.
  # Defaults to HtmlBasic.
  :report_types:
    - HtmlBasic     # Make an HTML summary report. (gcovr --html)
    - HtmlDetailed  # Make an HTML report with line by line coverage of each source file. (gcovr --html-details)
    - Text          # Make a Text report, which may be output to the console or a file.
    - Cobertura     # Make a Cobertura XML report. (gcovr --xml)
    - SonarQube     # Make a SonarQube XML report. (gcovr --sonarqube)
    - JSON          # Make a JSON report. (gcovr --json)

:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - gcov
    - xml_tests_report
...
